ALL_VARS = ["tmp_table_size", "password_reuse_interval", "slave_net_timeout",
    "hostname", "general_log_file", "ssl_crl", "ssl_key", "thread_pool_max_unused_threads",
    "persist_only_admin_x509_subject", "myisam_sort_buffer_size", "max_insert_delayed_threads",
    "external_user", "internal_tmp_mem_storage_engine", "skip_name_resolve",
    "character_set_server", "pseudo_thread_id", "key_cache_division_limit",
    "thread_pool_high_priority_connection", "myisam_stats_method", "general_log",
    "have_crypt", "max_sp_recursion_depth", "disconnect_on_expired_password",
    "show_create_table_verbosity", "character_sets_dir", "ft_boolean_syntax",
    "myisam_data_pointer_size", "show_compatibility_56", "caching_sha2_password_private_key_path",
    "log_error_filter_rules", "super_read_only", "table_open_cache", "protocol_version",
    "query_cache_type", "max_points_in_geometry", "multi_range_count", "secure_auth",
    "query_cache_min_res_unit",  "myisam_recover_options", "ft_min_word_len",
    "tx_isolation", "skip_external_locking", "schema_definition_cache", "bind_address",
    "caching_sha2_password_public_key_path", "new", "authentication_windows_use_principal_name",
    "auto_generate_certs", "min_examined_row_limit", "max_delayed_threads",
    "range_optimizer_max_mem_size", "end_markers_in_json", "persisted_globals_load",
    "collation_database", "sql_big_selects", "myisam_repair_threads", "mandatory_roles",
    "have_ssl", "delayed_insert_timeout", "keep_files_on_create", "locked_in_memory",
    "old_passwords", "max_error_count", "sql_safe_updates", "insert_id", "session_track_gtids",
    "character_set_client", "preload_buffer_size", "debug", "sql_auto_is_null",
    "sha256_password_private_key_path", "syseventlog.include_pid", "join_buffer_size",
    "datetime_format", "old_alter_table=ON", "old", "max_user_connections", "innodb_read_only",
    "tls_version", "version_compile_os", "automatic_sp_privileges", "flush_time", 
    "disabled_storage_engines", "net_retry_count", "warning_count", "skip_networking",
    "error_count", "have_statement_timeout", "flush", "max_heap_table_size",
    "foreign_key_checks=0", "log_throttle_queries_not_using_indexes", "delay_key_write",
    "character_set_filesystem", "autocommit", "slow_query_log", "named_pipe",
    "metadata_locks_cache_size", "completion_type", "slow_launch_time", "optimizer_trace_offset",
    "windowing_use_high_precision", "basedir", "cte_max_recursion_depth", "rand_seed1",
    "host_cache_size", "sql_quote_show_create", "log_error", "key_cache_age_threshold",
    "thread_pool_algorithm", "version_comment", "log_error_verbosity", "slow_query_log_file",
    "internal_tmp_disk_storage_engine", "max_connect_errors", "table_definition_cache",
    "default_authentication_plugin", "profiling",  "max_execution_time", "last_insert_id", 
    "init_file", "admin_port", "block_encryption_mode", "system_time_zone", "lower_case_file_system",
    "event_scheduler", "query_cache_limit", "performance_schema_max_digest_length",
    "lock_wait_timeout", "histogram_generation_max_mem_size", "myisam_use_mmap", "debug_sync",
    "net_write_timeout", "sha256_password_proxy_users", "time_format", "query_alloc_block_size",
    "proxy_user", "lc_messages", "license", "stored_program_cache", "have_compress", "innodb_open_files",
    "datadir", "have_geometry", "check_proxy_users", "sha256_password_public_key_path", "rbr_exec_mode",
    "max_prepared_stmt_count", "log_syslog_facility", "time_zone", "log_output",
    "myisam_mmap_size", "character_set_system", "metadata_locks_hash_instances",
    "have_symlink", "password_require_current", "default_password_lifetime",
    "key_buffer_size", "create_admin_listener_thread", "log_syslog_include_pid",
    "net_read_timeout", "syseventlog.tag", "optimizer_prune_level", "thread_pool_prio_kickup_timer",
    "lc_time_names", "parser_max_mem_size", "max_write_lock_count", "session_track_state_change",
    "show_old_temporals", "large_files_support", "shared_memory_base_name",
    "password_history", "ft_max_word_len", "ssl_crlpath", "lc_messages_dir",
    "authentication_windows_log_level", "max_length_for_sort_data", "collation_connection",
    "session_track_system_variables", "sql_select_limit", "query_prealloc_size",
    "mysql_native_password_proxy_users", "max_connections", "server_id", "ssl_capath",
    "optimizer_trace", "optimizer_trace_limit", "version_compile_zlib", "ft_query_expansion_limit",
    "core_file", "lower_case_table_names", "collation_server", "skip_show_database",
    "rand_seed2", "delayed_insert_limit", "group_concat_max_len", "transaction_alloc_block_size",
    "sql_notes", "log_slow_admin_statements", "pid_file", "max_seeks_for_key", "max_join_size",
    "log_warnings", "regexp_stack_limit", "old_alter_table", "back_log", "explicit_defaults_for_timestamp",
    "have_rtree_keys", "log_timestamps",  "log_slow_extra", "updatable_views_with_limit",
    "tmpdir", "sha256_password_auto_generate_rsa_keys", "wait_timeout", "admin_address",
    "slave_load_tmpdir", "avoid_temporal_upgrade", "query_cache_wlock_invalidate", "log_error_services",
    "thread_cache_size", "ssl_fips_mode", "socket", "date_format", "have_profiling",
    "use_secondary_engine", "thread_pool_size", "key_cache_block_size", "dragnet.log_error_filter_rules",
    "sort_buffer_size", "read_rnd_buffer_size", "session_track_transaction_info",
    "thread_handling", "transaction_isolation", "plugin_dir", "optimizer_search_depth",
    "shared_memory", "character_set_database", "ngram_token_size", "tx_read_only",
    "big_tables", "innodb_buffer_pool_in_core_file", "eq_range_index_dive_limit",
    "have_query_cache", "regexp_time_limit", "character_set_connection", "low_priority_updates",
    "default_tmp_storage_engine", "temptable_max_ram", "caching_sha2_password_auto_generate_rsa_keys",
    "pseudo_slave_mode", "syseventlog.facility", "foreign_key_checks = 0", "div_precision_increment",
    "mecab_rc_file", "interactive_timeout", "internal_tmp_disk_storage_engine=INNODB",
    "large_pages", "sql_require_primary_key", "offline_mode", "ssl_ca", "optimizer_switch",
    "information_schema_stats_expiry", "read_only", "have_dynamic_loading", "session_track_schema",
    "delayed_queue_size", "default_week_format", "transaction_read_only", "port", "max_allowed_packet",
    "secure_file_priv", "sql_log_off", "default_collation_for_utf8mb4", "autocommit=1", "read_buffer_size",
    "timestamp", "default_storage_engine", "connect_timeout", "max_sort_length", "concurrent_insert",
    "activate_all_roles_on_login", "local_infile", "ssl_cipher", "optimizer_trace_max_mem_size", "optimizer_trace_features",
    "sql_mode", "validate_user_plugins", "net_buffer_length", "thread_stack", "sql_buffer_result",
    "log_error_suppression_list", "unique_checks", "range_alloc_block_size", "max_digest_length",
    "character_set_results", "profiling_history_size", "version", "identity", "log_queries_not_using_indexes",
    "query_cache_size", "ssl_cert", "bulk_insert_buffer_size", "ft_stopword_file", "sql_warnings",
    "large_page_size", "foreign_key_checks",  "have_openssl", "resultset_metadata", "require_secure_transport",
    "myisam_max_sort_file_size", "max_tmp_tables", "version_compile_machine", "open_files_limit", "long_query_time",
    "table_open_cache_instances", "log_syslog", "transaction_prealloc_size",
    "stored_program_definition_cache", "thread_pool_stall_limit", "log_syslog_tag", "init_connect"]
