AUTHORIZED_VARS = ["auto_increment_increment", "auto_increment_offset", "autocommit",
    "binlog_direct_non_transactional_updates", "binlog_format", "binlog_row_image=image_type",
    "binlog_row_value_options", "binlog_rows_query_log_events", "block_encryption_mode",
    "bulk_insert_buffer_size", "completion_type", "default_week_format", "div_precision_increment",
    "end_markers_in_json", "eq_range_index_dive_limit", "explicit_defaults_for_timestamp",
    "foreign_key_checks", "group_concat_max_len", "gtid_next", "identity", "innodb_lock_wait_timeout",
    "innodb_parallel_read_threads", "innodb_strict_mode", "innodb_table_locks", "innodb_tmpdir",
    "insert_id", "internal_tmp_mem_storage_engine", "join_buffer_size", "keep_files_on_create",
    "last_insert_id", "lc_messages", "lc_time_names", "lock_wait_timeout", "long_query_time",
    "low_priority_updates", "max_allowed_packet", "max_delayed_threads", "max_error_count",
    "max_execution_time", "max_heap_table_size", "max_insert_delayed_threads", "max_join_size",
    "max_length_for_sort_data", "max_points_in_geometry", "max_seeks_for_key", "max_sort_length",
    "max_sp_recursion_depth", "max_tmp_tables", "max_user_connections", "min_examined_row_limit",
    "multi_range_count", "myisam_repair_threads", "myisam_sort_buffer_size", "myisam_stats_method",
    "ndb-allow-copying-alter-table", "ndb_autoincrement_prefetch_sz", "ndb_blob_write_batch_bytes",
    "ndb_deferred_constraints", "ndb_deferred_constraints", "ndb_force_send", "ndb_fully_replicated",
    "ndb_index_stat_enable", "ndb_index_stat_option", "ndb_join_pushdown", "ndb_log_bin",
    "ndb_log_exclusive_reads", "ndb_log_exclusive_reads", "ndb_row_checksum", "ndb_table_no_logging",
    "ndb_table_temporary", "ndb_use_exact_count", "ndb_use_transactions", "ndbinfo_max_bytes",
    "ndbinfo_max_rows", "ndbinfo_show_hidden", "ndbinfo_table_prefix", "net_buffer_length",
    "net_read_timeout", "net_retry_count", "net_write_timeout", "new", "old_alter_table",
    "old_passwords", "optimizer_prune_level", "optimizer_search_depth", "optimizer_switch",
    "optimizer_trace", "optimizer_trace_features", "optimizer_trace_limit",
    "optimizer_trace_max_mem_size", "optimizer_trace_offset", "original_commit_timestamp",
    "parser_max_mem_size", "preload_buffer_size", "profiling", "profiling_history_size",
    "pseudo_slave_mode", "pseudo_thread_id", "query_alloc_block_size", "query_cache_type",
    "query_cache_wlock_invalidate", "query_prealloc_size", "rand_seed1", "rand_seed2",
    "range_alloc_block_size", "range_optimizer_max_mem_size", "rbr_exec_mode", "read_buffer_size",
    "read_rnd_buffer_size", "resultset_metadata", "session_track_gtids", "session_track_schema",
    "session_track_state_change", "session_track_system_variables", "session_track_transaction_info",
    "show_create_table_verbosity", "show_old_temporals", "sort_buffer_size", "sql_auto_is_null",
    "sql_big_selects", "sql_buffer_result", "sql_log_bin", "sql_log_off", "sql_notes",
    "sql_require_primary_key", "sql_safe_updates", "sql_select_limit", "sql_warnings",
    "thread_pool_high_priority_connection", "thread_pool_prio_kickup_timer", "time_zone",
    "timestamp", "tmp_table_size", "transaction_alloc_block_size", "transaction_allow_batching",
    "transaction_isolation", "transaction_prealloc_size", "transaction_read_only",
    "transaction_write_set_extraction", "tx_isolation", "tx_read_only", "unique_checks",
    "updatable_views_with_limit", "use_secondary_engine", "version_tokens_session",
    "wait_timeout", "windowing_use_high_precision"]
