version: '3'

services:
  mdauth:
    build: .
    image: mdauth
    user: root
    container_name: mdauth
    ports:
      - "4444:80"
    networks:
      - mdauth
    restart: always
    volumes:
      - $PWD/www:/var/www/html

networks:
  mdauth:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.name: "mdauth"
